baseURL = 'https://krillnotes.com/'
languageCode = 'en-us'
title = 'Krillnotes'

[params]
  description = 'A local-first, hierarchical note-taking app. Scriptable, cross-platform, and yours.'
  tagline = 'Your notes. Your rules. Your device.'
  github = 'https://github.com/careck/krillnotes'

[menu]
  [[menu.main]]
    name = 'Features'
    url = '/#features'
    weight = 1
  [[menu.main]]
    name = 'Docs'
    url = '/docs/'
    weight = 2
  [[menu.main]]
    name = 'User Guide'
    url = '/docs/user-guide/'
    weight = 3
  [[menu.main]]
    name = 'Scripting'
    url = '/docs/scripting/'
    weight = 4
  [[menu.main]]
    name = 'Templates'
    url = '/templates/'
    weight = 5
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/careck/krillnotes'
    weight = 6

[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = false
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
